### ISSUE TITLE
File Format for Input Nuclear Segmentation in Lifted Multicut Algorithm

### ISSUE THREAD

**Issue by michaelschwimmer** [hci-unihd/plant-seg#100]
Hi! Thank you for this amazing work. 

I've segmented the nuclei for some images with another model that I've been training for a while, and wish to use these nuclear segmentations as seeds for membrane segmentation with PlantSeg. I've set it all up and have been trying with the label-map tiff file of labelled nuclei. It doesn't seem to work with this, does it only take another file format as input? I have a suspicion it's h5...

If it is do you know of a way I can convert, or ask the model to use my label-map image? Sorry if this is basic stuff, I'm a little new to this.

Thanks again and best wishes,

Michael

**Comment by wolny** [comment]
Hi @michaelschwimmer,

I'm happy to hear that `plantseg` has been useful in your research. Regarding your question: both tiff and hdf5 files are supported as input to plantseg LiftedMulticut segmentation. Regarding the nuclei images itself:
1. If you have a nuclei segmented already, please use the `is_segmentation: True` flag in the `segmentation` part for the config, e.g.
```
segmentation:
  # enable/disable segmentation
  state: True
  # path to the directory containing the nuclei predictions (either probability maps or segmentation)
  nuclei_predictions_path: PATH_TO_YOUR_NUCLEI_SEGMENTATION_FILE
  # whether the `nuclei_predictions_path` contains the probability maps (is_segmentation=False) or segmentation (is_segmentation=True)
  is_segmentation: True
  # Name of the algorithm to use for inferences
  name: "LiftedMulticut"
  # Segmentation specific parameters here
  # balance under-/over-segmentation; 0 - aim for undersegmentation, 1 - aim for oversegmentation
  beta: 0.65
  # directory where to save the results
  save_directory: OUTPUT_DIR
  # enable/disable watershed
  run_ws: True
  # use 2D instead of 3D watershed
  ws_2D: False
  # probability maps threshold
  ws_threshold: 0.5
  # set the minimum superpixels size
  ws_minsize: 50
  # sigma for the gaussian smoothing of the distance transform
  ws_sigma: 2.0
  # sigma for the gaussian smoothing of boundary
  ws_w_sigma: 0
  # set the minimum segment size in the final segmentation
  post_minsize: 100
```

2. I your nuclei file contains the probability maps (foreground semantic class), you need to use ``is_segmentation: False`, e.g.:
```
segmentation:
  # enable/disable segmentation
  state: True
  # path to the directory containing the nuclei predictions (either probability maps or segmentation)
  nuclei_predictions_path: PATH_TO_YOUR_NUCLEI_SEGMENTATION_FILE
  # whether the `nuclei_predictions_path` contains the probability maps (is_segmentation=False) or segmentation (is_segmentation=True)
  is_segmentation: False
  # Name of the algorithm to use for inferences
  name: "LiftedMulticut"
  # Segmentation specific parameters here
  # balance under-/over-segmentation; 0 - aim for undersegmentation, 1 - aim for oversegmentation
  beta: 0.65
  # directory where to save the results
  save_directory: OUTPUT_DIR
  # enable/disable watershed
  run_ws: True
  # use 2D instead of 3D watershed
  ws_2D: False
  # probability maps threshold
  ws_threshold: 0.5
  # set the minimum superpixels size
  ws_minsize: 50
  # sigma for the gaussian smoothing of the distance transform
  ws_sigma: 2.0
  # sigma for the gaussian smoothing of boundary
  ws_w_sigma: 0
  # set the minimum segment size in the final segmentation
  post_minsize: 100
```

I understand that your usecase is 1., so please make sure your config is correct. If it still doesn't work we would need your YAML config, your input membrane data and the nuclei segmentation file to investigate it further. One more tip: the shape of input membrane and the nuclei segmentation stacks has to be the same.

Best,
Adrian
