### ISSUE TITLE
`patch_halo` seems to be ignored

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#205]
I am fixing this right now.

My version: `v1.6.6`

My workflow: CLI

My config:

```yaml
cnn_prediction:
  # enable/disable UNet prediction
  state: True
  # key for H5 or ZARR, can be set to null if only one key exists in each file; null is recommended if the previous steps has state True
  key: Null
  # channel to use if input image has shape CZYX or CYX, otherwise set to null; null is recommended if the previous steps has state True
  channel: Null
  # Trained model name, more info on available models and custom models in the README
  model_name: 'PlantSeg_3Dnuc_platinum'
  # If a CUDA capable gpu is available and corrected setup use "cuda", if not you can use "cpu" for cpu only inference (slower)
  device: 'cuda'
  # (int or tuple) padding to be removed from each axis in a given patch in order to avoid checkerboard artifacts
  patch_halo: [32, 32, 32]
  # how many subprocesses to use for data loading
  num_workers: 8
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [45, 666, 516]
  # stride between patches will be computed as `stride_ratio * patch`
  # recommended values are in range `[0.5, 0.75]` to make sure the patches have enough overlap to get smooth prediction maps
  stride_ratio: 0.3
  # If "True" forces downloading networks from the online repos
  model_update: False
```

Workflow output:

```yaml
algorithm: UnetPredictions
file_suffix: _predictions
h5_output_key: predictions
input_channel: null
input_key: null
input_paths:
- /g/kreshuk/yu/Datasets/EMBL/CTischer2024Signalling/nuclei/PreProcessing/cell_t000_nuclei.h5
...
- /g/kreshuk/yu/Datasets/EMBL/CTischer2024Signalling/nuclei/PreProcessing/cell_t009_nuclei.h5
input_type: data_float32
model_name: PlantSeg_3Dnuc_platinum
out_ext: .h5
output_type: data_float32
patch:
- 45
- 300
- 300
predictor: !!python/object:plantseg.predictions.functional.array_predictor.ArrayPredictor
  batch_size: 2
  device: cuda
  disable_tqdm: false
  is_embedding: false
  model: !!python/object:plantseg.training.model.UNet3D
    ...
  out_channels: 2
  patch_halo:
  - 2
  - 4
  - 4
  verbose_logging: false
save_directory: /g/kreshuk/yu/Datasets/EMBL/CTischer2024Signalling/nuclei/PreProcessing/PlantSeg_3Dnuc_platinum
save_raw: false
state: true
stride_ratio: 0.3
```
