### ISSUE TITLE
Broken Environment - RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#228]
Installation with the following method results in `cudatookit==11.1`, which I guess is incompatible with `pytorch-cuda==12.1` and causes error during prediction.

```shell
$ mamba env create -f ./environment-dev.yaml
```
```yaml
name: plantseg-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pydantic>2
  - h5py
  - zarr
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - cudnn
  - pytorch
  - pytorch-cuda=12.1
  - python-elf
  - pyqt
  - napari
  - python-graphviz
```

Let's try both `conda` and `cuda-version==12.3`

**Comment by qin-yu** [comment]
Somehow `cudatoolkit` 11.1.74 from `nvidia` channel is installed.

```python
cudatoolkit               11.1.74              h6bb024c_0    nvidia
```

**Comment by qin-yu** [comment]
With the same conda and mamba installation, specifying `cuda-version==12.3` would avoid the installation for package `cudatoolkit`

```shell
$ mamba env create -f ./environment-dev.yaml
```
```yaml
name: plantseg-dev-cuda-12.3
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pydantic>2
  - h5py
  - zarr
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - cudnn
  - pytorch
  - pytorch-cuda=12.1
  - cuda-version==12.3
  - python-elf
  - pyqt
  - napari
  - python-graphviz
```
```python
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.4.127                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-version              12.3                 h32bc705_3    conda-forge
cudnn                     8.9.7.29             h092f7fd_3    conda-forge
```
